### ISSUE TITLE
colcon build fails

### ISSUE THREAD

**Issue by anu565lol** [aws-robotics/aws-iot-bridge-example#2]
I followed the step and got the following error while running colcon build
colcon build
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.powershell_command': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.defaults': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.all_shells': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.default_executor': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.extension_blacklist': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.home': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.log_level': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.log_path': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.cmake_command': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.ctest_command': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.argcomplete_timing': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.argument_parser.colcon': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.argument_parser.argcomplete': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.verb.test-result': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.verb.info': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.verb.list': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.verb.metadata': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.verb.extension-points': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.verb.extensions': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.verb.version-check': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.verb.build': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.verb.test': (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})
Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in load_entry_point
    return entry_point.load()
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 3.2.1 (/home/vizzbee/anaconda3/lib/python3.6/site-packages), Requirement.parse('pytest>=3.10'), {'pytest-rerunfailures'})

Traceback (most recent call last):
  File "/home/vizzbee/anaconda3/bin/colcon", line 10, in <module>
    sys.exit(main())
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/command.py", line 87, in main
    parser, command_name, verb_extensions, attribute='verb_name')
  File "/home/vizzbee/anaconda3/lib/python3.6/site-packages/colcon_core/command.py", line 298, in create_subparser
    assert verb_extensions, 'No verb extensions'
AssertionError: No verb extensions

Please Help

**Comment by anu565lol** [comment]
Worked by downgrading pytest to 3.10 and pyyaml to 3.13.

**Comment by maflo8** [comment]
Had the same problem, but didn't want to install this old version of pytest 3.10. The overall solution for solving this annoying issue:

pip install pytest-rerunfailures

to read more about look here: https://pypi.org/project/pytest-rerunfailures/

Now everything works fine and I can build my packages as usual!

**Comment by shanpenghui** [comment]
I use the command below to solve this problem:
`pip3 install pytest-rerunfailures`

and then recompile:
```
sudo rm -rf build/ install/ log/
colcon build
```
