### ISSUE TITLE
Can not run the bridge 'SyntaxError: invalid syntax'

### ISSUE THREAD

**Issue by mkusold** [aws-robotics/aws-iot-bridge-example#8]
**A reproducible test case or series of steps:**
Here is my Docker file:
```
FROM ros:kinetic

LABEL description="ROS prototype to connect to AWS IoT Services"

SHELL ["/bin/bash","-c"]

RUN apt-get update && apt-get install -y \
  # installing general project-independent development tools
  tmux \
  nano \
  vim \
  git \
  # installing important general ROS development dependencies
  openssh-client \
  openssh-server \
  python-rosdep \
  python-pip

# update pip
RUN pip install --upgrade pip

# Create local catkin workspace
ENV CATKIN_WS=/root/catkin_ws
RUN mkdir -p $CATKIN_WS/src
WORKDIR $CATKIN_WS/src

# install the latest major version (latest stable build) of the aws-iot-bridge-example repo
RUN git clone https://github.com/aws-robotics/aws-iot-bridge-example.git -b release-v1

# Initialize local catkin workspace
RUN source /opt/ros/${ROS_DISTRO}/setup.bash \
  # Update apt-get because its cache is always cleared after installs to keep image size down
  && apt-get update \
  # Install dependencies
  && cd $CATKIN_WS \
  && rosdep install -y --from-paths . --ignore-src -r --rosdistro ${ROS_DISTRO} \
  # Build catkin workspace
  && catkin_make

# copy local certificates to the container node config
COPY certs $CATKIN_WS/src/aws-iot-bridge-example/aws_iot_mqtt_bridge/config/certs
# copy configuration file to container node config
COPY aws_iot_params.yaml $CATKIN_WS/src/aws-iot-bridge-example/aws_iot_mqtt_bridge/config/aws_iot_params.yaml
# copy the launch file
COPY aws_iot_bridge.launch $CATKIN_WS/src/aws-iot-bridge-example/aws_iot_mqtt_bridge/launch/aws_iot_bridge.launch

# open up the bash script for interactivity
CMD ["bash"]
```

 **In terms of how I ran the program, here are my steps**
```
1. In the terminal, source your workspace `source ../devel/setup.bash`
2. Run `cd ~/catkin_ws/src/aws-iot-bridge-example/aws_iot_mqtt_bridge`
3. Run `roslaunch aws_iot_mqtt_bridge aws_iot_bridge.launch bridge_params:=config/aws_iot_params.yaml`
```
I have tested out all of the AWS IoT connections / policies / certs etc. outside of ROS and have validated that they work.
I expect that with my configurations, this package should work as well when I run the roslaunch; however, instead I get this result:

```
SUMMARY
========

PARAMETERS
 * /mqtt_bridge/client/protocol: 4
 * /mqtt_bridge/connection/host: RETRACTED...
 * /mqtt_bridge/connection/keepalive: 60
 * /mqtt_bridge/connection/port: 8883
 * /mqtt_bridge/mqtt/client/protocol: 4
 * /mqtt_bridge/mqtt/connection/host: RETRACTED...
 * /mqtt_bridge/mqtt/connection/keepalive: 60
 * /mqtt_bridge/mqtt/connection/port: 8883
 * /mqtt_bridge/mqtt/tls/ca_certs: /root/catkin_ws/s...
 * /mqtt_bridge/mqtt/tls/certfile: /root/catkin_ws/s...
 * /mqtt_bridge/mqtt/tls/keyfile: /root/catkin_ws/s...
 * /mqtt_bridge/mqtt/tls/tls_insecure: False
 * /mqtt_bridge/mqtt/tls/tls_version: 5
 * /mqtt_bridge/tls/ca_certs: certs/root-CA.crt
 * /mqtt_bridge/tls/certfile: certs/GroverBot1....
 * /mqtt_bridge/tls/keyfile: certs/GroverBot1....
 * /mqtt_bridge/tls/tls_insecure: False
 * /mqtt_bridge/tls/tls_version: 5
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    mqtt_bridge (mqtt_bridge/mqtt_bridge_node.py)

auto-starting new master
process[master]: started with pid [68]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 95d4ea2a-2119-11ea-90f6-0242ac130002
process[rosout-1]: started with pid [81]
started core service [/rosout]
running rosparam delete /mqtt_bridge/
ERROR: parameter [/mqtt_bridge] is not set
process[mqtt_bridge-2]: started with pid [103]
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/mqtt_bridge/mqtt_bridge_node.py", line 5, in <module>
    from mqtt_bridge.app import mqtt_bridge_node
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/mqtt_bridge/app.py", line 4, in <module>
    import inject
  File "/usr/local/lib/python2.7/dist-packages/inject/__init__.py", line 105
    def install(self, config: BinderCallable) -> 'Binder':
                            ^
SyntaxError: invalid syntax
[mqtt_bridge-2] process has died [pid 103, exit code 1, cmd /opt/ros/kinetic/lib/mqtt_bridge/mqtt_bridge_node.py __name:=mqtt_bridge __log:=/root/.ros/log/95d4ea2a-2119-11ea-90f6-0242ac130002/mqtt_bridge-2.log].
log file: /root/.ros/log/95d4ea2a-2119-11ea-90f6-0242ac130002/mqtt_bridge-2*.log
```

**Comment by edmodi** [comment]
I have the same error. Thanks

**Comment by mkusold** [comment]
From further investigation, it seems like there's some issue with the mqtt_bridge package. Specifically the 'inject' package. There are a couple of related reported issues in their repo, but I followed suggestions there to no avail. 

I tried adding apt-get install ros-kinetic-rosbridge-suite and also installing a specific 'inject' version within the container.
 I also tried deleting the ```<rosparam command="delete" param="" />``` line from the launch file so that I wouldn't get the 'ERROR: parameter [/mqtt_bridge] is not set' issue. (which did indeed get rid of this Error!)

 Separate and together, these attempts result in the same 'SyntaxError: invalid syntax' result. So I still can not get this package to run.

**Comment by edmodi** [comment]
Could be the python version? I use 2.7 native with ROS Kinetic

**Comment by mm318** [comment]
The minimal way to reproduce this syntax issue is
```
# starting with a kinetic container
sudo apt install ros-kinetic-mqtt-bridge
sudo -H pip install -U inject
source /opt/ros/kinetic/setup.bash
rosrun mqtt_bridge mqtt_bridge_node.py
```
The issue doesn't seem to be related to this repo, but rather with [mqtt_bridge](https://github.com/groove-x/mqtt_bridge) or [inject](https://github.com/ivankorobkov/python-inject)

**Comment by mm318** [comment]
As a workaround, can you please try installing an older version of `inject`? For example:
```
# in a kinetic container
sudo pip uninstall inject
sudo -H pip install inject==3.5.4
```

**Comment by mm318** [comment]
Since this issue has been inactive for a month, I'm going to close it for now.
